### ISSUE TITLE
Persona #3 - General interest student 

### ISSUE THREAD

**Issue by katz0014** [MTM6330-F18/final-SASSykatz#13]
Shawn will create a persona of a prospective student who is generally interested in learning the topics covered in the program for a myriad reasons.

**Comment by pepi0039** [comment]
**David**
**26**
**Technology Skills: Medium**

David is looking at going back to school. He graduated from a local university a few years prior and hasn't landed job he saw himself in yet. 

David is fairly tech-savvy and has a decent understanding of many of the subjects offered in this course, but doesn't have a firm grasp on any. He feels like a multimedia course will help him up his skills and find a job in a more interesting field and is more future-proof. He's particularly interested in the coding and video aspects the program offers.

_"I found myself stuck in my current job. Waking up for work every morning felt like a chore and I wasn't enjoying it anymore. I wanted to try and enter a field that was more cutting edge and allowed me to be more creative._ 

For someone who has a general interest in what IMD offers, this program looks very well suited for David.
