### ISSUE TITLE
Research one post-secondary institution's digital media school by Friday 

### ISSUE THREAD

**Issue by katz0014** [MTM6330-F18/final-SASSykatz#17]
Place the school's name here, what you like, don't like, what you think we should include and exclude. Also provide link to site page.

**Comment by katz0014** [comment]
I looked at George Brown College. They had all of the elements for the description at the top with labeled tabs. The user could just see the tab title and click on it to reveal its contents. For example, there is 'Overview', 'Full Description', 'Courses', 'Career and Postgraduate Study Opportunities', 'Tuition & Fees' and more. I like this tab system as it allows the visitor to see all of the options in an easy to read format at the top, rather than having to scroll for the information. 
However, I didn't like that as you scroll the nav bar stays with the user. I think it's too large and bulky and makes it hard to read the main content. 

https://www.georgebrown.ca/programs/interaction-design-program-g113/#overviewContent

**Comment by brau0060** [comment]
### OCAD University
I looked into OCAD University of Toronto. What I found was that their information is very minimal and organized. Under their Integrated Media Program, they have organized all the important information under unfoldable cards. They have filled the left side of the web page with unfoldable cards and the right side with buttons leading to other information regarding the program.

### Their top cards are.
•	More about Intergrader Media Program
•	Admission Requirements
•	Jobs You Can Get
•	Co-ops/Internships

And they had all four years under there own collapsible card.

I really like how their isn't much scrolling on the website and the user is able to chooses what he/she wants to see.

Link: https://www.ocadu.ca/admissions/programs/integrated-media.htm 

![screenshot- 131](https://user-images.githubusercontent.com/43067929/48243424-5c784280-e3ae-11e8-83bd-998f8e9e79c7.jpg)
