### ISSUE TITLE
Review Algonquin website for preferences 

### ISSUE THREAD

**Issue by katz0014** [MTM6330-F18/final-SASSykatz#18]

**Comment by StephenGagne** [comment]
Main page.

Overview
The spacing between BYOD and “success factors” is not enough to make it clear that they are separate items.
The questionnaire about whether or not I am well suited to the program pops up constantly and will not give me results unless I provide personal information. 

Courses.
This section is well laid out. The only concerns are that the “read more” tags are often inserted midword and that “choose one from equivalencies” is not a clear way to say general education elective.

Careers & Pathways
The only careers listed appear to be in video production. No mention is made of web developer or UX design.

Fees and Expenses
This is a huge block of text that could be much better laid out. Also, it is not clear why students in video would have to buy a 70-200 f4 L series lens or why we must use Canon cameras. Neither of these statements is factual.

Application Information
Lots of text, could be laid out far better.

Additional Information
This tab does not appear to serve any purpose other than to provide Katie’s contact information.


Other Pages
The Student Experience Tab shows a video that, while a good overview of the program, is very much out of date. It mentions a field placement program that no longer exists. Additionally, the name of the program is shown as Interactive Multimedia Developer.
FAQs
The quality of English on this page is inconsistent. For example, the Equipment section stipulates that the college provides “excellent” for students to use or borrow.
The section regarding equipment is misleading. It suggests that a student could get through this program without buying a laptop.

Client Projects
This page appears to be intended to attract clients for the Applied Projects class. For some reason, when visiting it, I am still asked to fill out the survey about whether the program is right for me.

**Comment by StephenGagne** [comment]
Done. See comments above.
